require("sparks.remap")
vim.cmd('set number')
vim.cmd('set tabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('colorscheme kanagawa-dragon')
vim.cmd('colorscheme catppuccin')
vim.cmd('colorscheme dracula')
require("autoclose").setup()
require("mason").setup()
